#!/usr/bin/env bash
set -euo pipefail

APP_NAME="sketchflow-preact-demo"
LAYOUT_ENGINE="passthrough"
ADAPTER_OPTIONS=()
APP_NAME_SET=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --layout)
      [[ $# -lt 2 ]] && { echo "--layout requires an argument" >&2; exit 1; }
      LAYOUT_ENGINE="$2"
      shift 2
      ;;
    --adapter-option)
      [[ $# -lt 2 ]] && { echo "--adapter-option requires an argument" >&2; exit 1; }
      ADAPTER_OPTIONS+=("$2")
      shift 2
      ;;
    -h|--help)
      echo "Usage: $0 [app-name] [--layout engine] [--adapter-option key=value]..."
      exit 0
      ;;
    *)
      if [[ $APP_NAME_SET -eq 0 ]]; then
        APP_NAME="$1"
        APP_NAME_SET=1
        shift
      else
        echo "Unknown argument: $1" >&2
        exit 1
      fi
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
OUTPUT_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "$OUTPUT_DIR"
}
trap cleanup EXIT

pnpm --dir "$REPO_ROOT" --filter @sketchflow/cli run build >/dev/null 2>&1

CLI_ARGS=(
  --input "$REPO_ROOT/packages/cli/examples/sample-document.json"
  --framework preact
  --layout "$LAYOUT_ENGINE"
  --out "$OUTPUT_DIR"
)

for opt in "${ADAPTER_OPTIONS[@]}"; do
  CLI_ARGS+=(--adapter-option "$opt")
done

CLI_BIN="$REPO_ROOT/packages/cli/dist/index.js"
node "$CLI_BIN" generate "${CLI_ARGS[@]}"

pnpm create vite "$APP_NAME" --template preact-ts >/dev/null 2>&1

cd "$APP_NAME"

mkdir -p src/components

component_file=$(find "$OUTPUT_DIR" -maxdepth 1 -type f -name '*.tsx' | head -n1)

if [[ -z "$component_file" ]]; then
  echo "No Preact component file generated by Sketchflow CLI" >&2
  exit 1
fi

component_basename=$(basename "$component_file")

cp "$component_file" "src/components/$component_basename"

cat <<EOF > src/app.tsx
import { FunctionalComponent } from "preact";
import GeneratedComponent from "./components/${component_basename%.tsx}";

const App: FunctionalComponent = () => (
  <main class="app-shell">
    <GeneratedComponent />
  </main>
);

export default App;
EOF

cat <<'EOF' > src/app.css
.app-shell {
  margin: 0 auto;
  max-width: 960px;
}
EOF

pnpm install >/dev/null 2>&1

echo "Preact starter created in $APP_NAME. Run 'cd $APP_NAME && pnpm dev' to start the dev server."
