import {
  AdapterContext,
  AdapterResult,
  FrameworkAdapter,
  SketchNode,
  registerFrameworkAdapter
} from "@sketchflow/core";

export interface SvelteAdapterOptions {
  componentName?: string;
}

const DEFAULT_COMPONENT_NAME = "GeneratedScreen";

const toInlineStyle = (layout: SketchNode["layout"]): string => {
  const declarations = [
    `position: absolute`,
    `left: ${layout.x}px`,
    `top: ${layout.y}px`,
    `width: ${layout.width}px`,
    `height: ${layout.height}px`
  ];

  if (typeof layout.rotation === "number") {
    declarations.push(`transform: rotate(${layout.rotation}deg)`);
  }

  return declarations.join("; ");
};

const indent = (depth: number) => "  ".repeat(depth);

const renderNodes = (nodes: SketchNode[], depth = 2): string => {
  return nodes
    .map((node) => {
      const style = toInlineStyle(node.layout);
      const childContent = node.children.length ? `\n${renderNodes(node.children, depth + 1)}\n${indent(depth)}` : "";

      switch (node.type) {
        case "text": {
          const textValue = node.props?.text ?? node.name ?? "Label";
          return `${indent(depth)}<span style="${style}">${textValue}</span>`;
        }
        case "image": {
          const src = node.props?.src ?? "";
          const alt = node.props?.alt ?? node.name ?? "image";
          return `${indent(depth)}<img style="${style}" src="${src}" alt="${alt}" />`;
        }
        case "component":
        case "group":
        case "frame":
        default: {
          return `${indent(depth)}<div style="${style}">${childContent}</div>`;
        }
      }
    })
    .join("\n");
};

const generateSvelteComponent = (context: AdapterContext, options: SvelteAdapterOptions): AdapterResult => {
  const componentName = options.componentName ?? DEFAULT_COMPONENT_NAME;
  const templateBody = renderNodes(context.layout);

  const contents = `<script lang="ts">
  // Component generated by Sketchflow Svelte adapter
</script>

<div class="sketchflow-root" style="position: relative">
${templateBody}
</div>
`;

  return {
    files: [
      {
        path: `${componentName}.svelte`,
        contents
      }
    ]
  } satisfies AdapterResult;
};

export const svelteAdapter: FrameworkAdapter = {
  framework: "svelte",
  language: "ts",
  introspect: (context: AdapterContext) => ({
    nodeCount: context.layout.length,
    components: context.layout.filter((node) => node.type === "component").length
  }),
  generate: (context: AdapterContext) => {
    const options = (context.options ?? {}) as SvelteAdapterOptions;
    return generateSvelteComponent(context, options);
  }
};

export const registerSvelteAdapter = () => {
  registerFrameworkAdapter(svelteAdapter);
  return svelteAdapter;
};
