#!/usr/bin/env bash
set -euo pipefail

APP_NAME="sketchflow-angular-demo"
LAYOUT_ENGINE="passthrough"
ADAPTER_OPTIONS=()
APP_NAME_SET=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --layout)
      [[ $# -lt 2 ]] && { echo "--layout requires an argument" >&2; exit 1; }
      LAYOUT_ENGINE="$2"
      shift 2
      ;;
    --adapter-option)
      [[ $# -lt 2 ]] && { echo "--adapter-option requires an argument" >&2; exit 1; }
      ADAPTER_OPTIONS+=("$2")
      shift 2
      ;;
    -h|--help)
      echo "Usage: $0 [app-name] [--layout engine] [--adapter-option key=value]..."
      exit 0
      ;;
    *)
      if [[ $APP_NAME_SET -eq 0 ]]; then
        APP_NAME="$1"
        APP_NAME_SET=1
        shift
      else
        echo "Unknown argument: $1" >&2
        exit 1
      fi
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
OUTPUT_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "$OUTPUT_DIR"
}
trap cleanup EXIT

pnpm --dir "$REPO_ROOT" --filter @sketchflow/cli run build >/dev/null 2>&1

CLI_ARGS=(
  --input "$REPO_ROOT/packages/cli/examples/sample-document.json"
  --framework angular
  --layout "$LAYOUT_ENGINE"
  --out "$OUTPUT_DIR"
)

for opt in "${ADAPTER_OPTIONS[@]}"; do
  CLI_ARGS+=(--adapter-option "$opt")
done

CLI_BIN="$REPO_ROOT/packages/cli/dist/index.js"
node "$CLI_BIN" generate "${CLI_ARGS[@]}"

pnpm dlx @angular/cli@latest new "$APP_NAME" \
  --style=scss \
  --routing=false \
  --skip-git \
  --package-manager=pnpm \
  >/dev/null 2>&1

cd "$APP_NAME"

mkdir -p src/app/generated

component_ts=$(find "$OUTPUT_DIR" -maxdepth 1 -type f -name '*.ts' | head -n1)

if [[ -z "$component_ts" ]]; then
  echo "No Angular component generated by Sketchflow CLI" >&2
  exit 1
fi

component_basename=$(basename "$component_ts")
component_stem="${component_basename%.ts}"

component_html="$OUTPUT_DIR/${component_stem}.html"
component_css="$OUTPUT_DIR/${component_stem}.css"

if [[ ! -f "$component_html" || ! -f "$component_css" ]]; then
  echo "Generated Angular component assets missing (expected ${component_stem}.{html,css})" >&2
  exit 1
fi

selector=$(printf '%s' "$component_stem" | sed 's/[^[:alnum:]]/-/g' | sed 's/-\{1,\}/-/g' | sed 's/^-\|-$//g' | tr '[:upper:]' '[:lower:]')

cp "$component_ts" "src/app/generated/${component_basename}"
cp "$component_html" "src/app/generated/${component_stem}.html"
cp "$component_css" "src/app/generated/${component_stem}.css"

cat <<EOF > src/app/app.module.ts
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { AppComponent } from "./app.component";
import { GeneratedComponent } from "./generated/${component_stem}";

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, GeneratedComponent],
  bootstrap: [AppComponent]
})
export class AppModule {}
EOF

cat <<EOF > src/app/app.component.html
<main class="app-shell">
  <${selector}></${selector}>
</main>
EOF

cat <<'EOF' > src/app/app.component.scss
.app-shell {
  margin: 0 auto;
  max-width: 960px;
}
EOF

pnpm install >/dev/null 2>&1

echo "Angular starter created in $APP_NAME. Run 'cd $APP_NAME && pnpm start' to launch the dev server."
